### ISSUE TITLE
一些小问题

### ISSUE THREAD

**Issue by cloudfox2** [SilenceDut/KnowWeather#1]
1. 通知栏布局不垂直居中, 很难受
2. 在通知栏打开能不显示splash页吗
3. 上方的view必须下拉超过一半才会展开, 往上收就没这个问题
4. 第二第三个tab里的空白间距不一样
5. 3个tab的图标不一样大, 第一个第三个太小了

**Comment by SilenceDut** [comment]
非常感谢你的反馈，这里逐一回答一下有你的问题，

1.通知栏布局问题，由于是自定义通知栏，可能是由于不同手机适配显示的问题，我会好好看一下
2.目前的设计是这样，要不后期加个开关选项。
3.是故意为之，也就是弹性滑动，避免误操作，这是CollapsingToolbarLayout的一个属性
4.是自己设计的不一样的，为了滑动时看到差别
5.选中时变大变色，突出当前tab,你选到不同的tab时也会改变大小。

当然你可以自己修改这些，都是很好修改的部分，然后自己使用。图标的样式，颜色，大小等在http://www.iconfont.cn   或   https://icons8.com

**Comment by cloudfox2** [comment]
并没有选中变大, 小米5

**Comment by SilenceDut** [comment]
那应该是bug了，我这没出现，我看看能不能找个小米5试试，顺便看看通知栏

**Comment by ChinaVolvocars** [comment]
为什么需要那么多权限？？？
我看很多都没有用啊，还要去申请

**Comment by MiHiTiger** [comment]
我看很多都没有用啊，还要去申请

**Comment by SilenceDut** [comment]
使用腾讯bugly的sdk时推荐申请的，主要针对Android N

**Comment by cloudfox2** [comment]
通知栏也没常驻

**Comment by SilenceDut** [comment]
什么手机，版本

**Comment by cloudfox2** [comment]
小米5, 1.1.5
还是没有垂直居中

**Comment by SilenceDut** [comment]
没找到小米5。。。，通知栏截个图看看
