### ISSUE TITLE
为什么安装不上，提示无法创建文件

### ISSUE THREAD

**Issue by yjandroid** [SilenceDut/KnowWeather#12]

**Comment by yjandroid** [comment]
还有你的deom我下载安装了以后闪退

**Comment by SilenceDut** [comment]
感谢提醒,现在可以了

**Comment by yjandroid** [comment]
还是无法运行
Error:Execution failed for task ':app:packageDebug'.
> Cannot create directory 
都不知道怎么修改

**Comment by SilenceDut** [comment]
clean build 试试，如果还是不行加我Q3026354251
