### ISSUE TITLE
Execution failed for task ':app:packageDebug'.

### ISSUE THREAD

**Issue by ghost** [SilenceDut/KnowWeather#15]
Error:Execution failed for task ':app:packageDebug'.
> Cannot create directory D:\code\KnowWeather\app\build\outputs\apk\debug\D:\code\KnowWeather\app\build\intermediates\instant-run-resources

**Comment by xroc** [comment]
把下面这段代码注释
applicationVariants.all { variant ->
        variant.outputs.each { output ->
            output.outputFileName = new File(
                    output.outputFile.getParent(),
                    "knowweather.apk".toLowerCase())
        }
    }
或者替换成下面
applicationVariants.all { variant ->
        variant.outputs.all { output ->  // each 改为 all
            def fileName = "${variant.versionName}_release.apk"
            def outFile = output.outputFile
            if (outFile != null && outFile.name.endsWith('.apk')) {
                outputFileName = fileName  //  output.outputFile 改为 outputFileName
            }
            //删除unaligned apk
            if (output.zipAlign != null) {
                output.zipAlign.doLast {
//                    output.zipAlign.inputFile.delete()
                }
            }
        }
    }
主要原因是gradle切换到3.0以上打包出现的问题
