### ISSUE TITLE
improperly called by android.support.v7.widget.AppCompatTextView

### ISSUE THREAD

**Issue by ungenius** [SilenceDut/KnowWeather#8]
我的日志一直会打印这样的warning
08-09 11:01:02.368 13762-13762/com.allen.onlyweather W/View: requestLayout() improperly called by android.support.v7.widget.AppCompatTextView{7aa1f84 V.ED..... ........ 856,43-924,124 #7f0d007e app:id/tv_title_temp} during second layout pass: posting in next frame
08-09 11:01:02.382 13762-13762/com.allen.onlyweather W/View: requestLayout() improperly called by android.support.v7.widget.AppCompatTextView{7aa1f84 V.ED..... ......ID 856,43-924,124 #7f0d007e app:id/tv_title_temp} during layout: running second layout pass
请问这个如何解决还是说直接忽略呢，但是在您的项目里面却没有看见这样的日志呢。

**Comment by SilenceDut** [comment]
忽略就行了
