### ISSUE TITLE
 W/View: requestLayout() improperly called by android.support.v7.widget.AppCompatTextView

### ISSUE THREAD

**Issue by ungenius** [SilenceDut/KnowWeather#9]
您好，非常抱歉打扰您，还是我刚刚的那个问题，这个warning应该如何忽略呢？还有为什么运行您的项目没有这个warning呢？

**Comment by SilenceDut** [comment]
做的有些久了，记不起来了，记得以前也有，可能和support版本有关

**Comment by ungenius** [comment]
恩，我觉得也是和版本有关系，您的项目support版本是23.2.1，我的是25.3.1，不过我在StackOverFlow上找到一个解决方法，具体见https://stackoverflow.com/a/45360715/8153319
是设置TextView的visiblity="gone"，然后再onOffsetChangeListener中先判断TextView的visibility再去textView.setText("***")。我在我的项目中实验了是可行的。然后这是他的回答
onOffsetChanged() is called so many times and android is throwing that warning because you are requesting layout as part of toolbar_title.setText("Dashboard"); . What you should do is , use a boolean flag and call it only once if the condition is met or check the VISIBILITY flag for the toolbar text view ,something like this.

**Comment by Caoyaping** [comment]
您好，很抱歉打扰您，下载了您的项目，可以完美运行，只是这种依赖怎么添加了？api "com.github.SilenceDut.Hub:hub:$gradle.hub"

**Comment by Caoyaping** [comment]
您好 非常抱歉打扰您
我叫曹亚平，目前在柬埔寨从事软件维护工作，前两天偶然在github看到你开源的KnowWeather项目，很喜欢你简介优雅的设计风格。只是由于本人资质太浅，有些代码不明所以。希望您能指点一二，不胜感激。
非常感谢您宝贵的时间。

**Comment by SilenceDut** [comment]
api  的引用方式是gradel 3.0的引入方式

**Comment by Caoyaping** [comment]
可以加您QQ好友吗？ 在研读你的代码很多障碍的 望指点一二，  不胜感激了~

**Comment by SilenceDut** [comment]
3026354251 工作时间可能没太多时间回复
